apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: mlops
    secureJsonData:
      password: mlops
    jsonData:
      database: mlops
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
